// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCj1AuqBpwCqWFvDWa20dUF7_cEdNnixB8',
    appId: '1:1000102029834:web:0ccddc6137d85e61038df3',
    messagingSenderId: '1000102029834',
    projectId: 'bookproject-28394',
    authDomain: 'bookproject-28394.firebaseapp.com',
    storageBucket: 'bookproject-28394.firebasestorage.app',
    measurementId: 'G-CYMMTLY9DF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRmxXNas3AZKMfbd6V7qaH9Tc6fomolrU',
    appId: '1:1000102029834:android:fa73488df67c925a038df3',
    messagingSenderId: '1000102029834',
    projectId: 'bookproject-28394',
    storageBucket: 'bookproject-28394.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD85A_qoeBG2tdWu9u2dKZNQfIZH60jYYc',
    appId: '1:1000102029834:ios:bb906649a794ce73038df3',
    messagingSenderId: '1000102029834',
    projectId: 'bookproject-28394',
    storageBucket: 'bookproject-28394.firebasestorage.app',
    iosBundleId: 'com.example.bookproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD85A_qoeBG2tdWu9u2dKZNQfIZH60jYYc',
    appId: '1:1000102029834:ios:bb906649a794ce73038df3',
    messagingSenderId: '1000102029834',
    projectId: 'bookproject-28394',
    storageBucket: 'bookproject-28394.firebasestorage.app',
    iosBundleId: 'com.example.bookproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCj1AuqBpwCqWFvDWa20dUF7_cEdNnixB8',
    appId: '1:1000102029834:web:e488e08edef49163038df3',
    messagingSenderId: '1000102029834',
    projectId: 'bookproject-28394',
    authDomain: 'bookproject-28394.firebaseapp.com',
    storageBucket: 'bookproject-28394.firebasestorage.app',
    measurementId: 'G-G0WR9L2393',
  );
}
